/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexaoBanco;

import java.sql.Connection;

public class App {
    

    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        
        
        // Criar tabela
       CriarTabela.criarTabelaUsuarios(conexao);
       
       //Inserir um usuário na tabela
       InserirUsuario.inserirUsuario(conexao, "Felipe", "felipe@mail.com");
       
      System.out.println( ListarUsuarios.listarUsuarios(conexao));
    }
}
