/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pokemon;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Aluno
 */
public class Treinador extends javax.swing.JFrame {
     ArrayList<Pokemon> computador = new ArrayList<>(); // Criar um ArrayList
    ArrayList<Pokemon> mochila = new ArrayList<>(); // Criar um ArrayList
    private DefaultListModel<String> modeloLista;
    private DefaultListModel<String> modeloLista2;
    
    /**
     * Creates new form Treinador
     */
    public Treinador() {
        initComponents();
        computador.add(new Pokemon("Pikachu", "Elétrico", 10));
        computador.add(new Pokemon("Charmander", "Fogo", 12));
        computador.add(new Pokemon("Squirtle", "Água", 11));
        computador.add(new Pokemon("Bulbasaur", "Grama", 13));
        computador.add(new Pokemon("Jigglypuff", "Normal", 8));
        computador.add(new Pokemon("Gengar", "Fantasma", 15));
        computador.add(new Pokemon("Snorlax", "Normal", 14));
        computador.add(new Pokemon("Eevee", "Normal", 10));
        computador.add(new Pokemon("Magikarp", "Água", 5));
        computador.add(new Pokemon("Dragonite", "Dragão", 25));
        computador.add(new Pokemon("Mewtwo", "Psíquico", 30));
        computador.add(new Pokemon("Arcanine", "Fogo", 18));
        computador.add(new Pokemon("Lapras", "Água", 20));
        computador.add(new Pokemon("Gyarados", "Água", 22));
        computador.add(new Pokemon("Vaporeon", "Água", 19));
        computador.add(new Pokemon("Jolteon", "Elétrico", 19));
        computador.add(new Pokemon("Flareon", "Fogo", 19));
        computador.add(new Pokemon("Alakazam", "Psíquico", 21));
        computador.add(new Pokemon("Machamp", "Lutador", 23));
        computador.add(new Pokemon("Ditto", "Normal", 7));
        
         modeloLista = new DefaultListModel<>();
         modeloLista2 = new DefaultListModel<>();
         
        listaComputador.setModel(modeloLista);
        listaMochila.setModel(modeloLista2);
        
        for (Pokemon poke: computador) {
            modeloLista.addElement(poke.nome);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaComputador = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaMochila = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdicionar.setText("Adicionar Pokémon");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover Pokémon");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listaComputador);

        jScrollPane2.setViewportView(listaMochila);

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel1.setText("Computador");

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 12)); // NOI18N
        jLabel2.setText("Mochila");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnAdicionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        //Pega o índice do item selecionado
        int index = listaComputador.getSelectedIndex();
        //Se eu não selecionei nada ainda, ele mostra uma janela que contém a mensagem abaixo
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Pokémon primeiro!");
            return;
        }
        // A variável pokemon pega o pokemon de acordo com o índice e armazena nela
        Pokemon pokemon = computador.get(index);
        // Aqui, eu removo o pokemon do ArrayList computador
        computador.remove(index);
        // Aqui, eu adiciono o pokemon ao ArrayList mochila
        mochila.add(pokemon);

        atualizarLista();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        //Pega o índice do item selecionado na lista da minha mochila
        int index = listaMochila.getSelectedIndex();
        //Se eu não selecionei nada ainda, ele mostra uma janela que contém a mensagem abaixo
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um Pokémon da mochila!");
            return;
        }
         // A variável pokemon pega o pokemon de acordo com o índice e armazena nela
        Pokemon pokemon = mochila.get(index);
        // Aqui, eu removo o pokemon do ArrayList mochila
        mochila.remove(index);
        // Aqui, eu adiciono o pokemon ao ArrayList computador
        computador.add(0,pokemon);

        atualizarLista();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void atualizarLista() {
         // Limpa os modelos das listas
         modeloLista.clear();
         modeloLista2.clear();

        // Atualiza a lista do computador com os Pokémon disponíveis
        // "Para cada poke dentro do ArrayList computador, faça algo"
        for (Pokemon poke : computador) {
            // E o que ele faz? Chama o método addElement para adicionar à lista o nome de cada pokémon
            modeloLista.addElement(poke.nome);
        }

        // Atualiza a lista da mochila com os Pokémon já adicionados
        // "Para cada poke dentro do ArrayList mochila, faça algo"
        for (Pokemon poke : mochila) {
             // De novo, ele chama o método addElement mas agora adiciona o nome, o tipo e o nível de cada pokemon à lista da mochila
            modeloLista2.addElement(poke.nome + " do tipo " + poke.tipo + " de nível " + poke.nivel);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Treinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Treinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Treinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Treinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Treinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaComputador;
    private javax.swing.JList<String> listaMochila;
    // End of variables declaration//GEN-END:variables
}
