/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uc9.charactersheetgenerator;

import java.util.ArrayList;

/**
 *
 * @author Aluno
 */
public class CharacterSheet extends javax.swing.JFrame {

    /**
     * Creates new form Generator
     */
    public CharacterSheet(String name, String age, String race, String chClass, ArrayList<String> feats) {
        initComponents();
        this.chName.setText(name);
        this.chAge.setText(age);
        this.chRace.setText(race);
        this.chClass.setText(chClass);
        extract(feats);
    }
    
    public CharacterSheet(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblRace = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblFaS = new javax.swing.JLabel();
        chName = new javax.swing.JLabel();
        chAge = new javax.swing.JLabel();
        chRace = new javax.swing.JLabel();
        chFaS = new javax.swing.JLabel();
        chClass = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        lblName.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 204, 0));
        lblName.setText("Name");

        lblAge.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 204, 0));
        lblAge.setText("Age");

        lblRace.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lblRace.setForeground(new java.awt.Color(255, 204, 0));
        lblRace.setText("Race");

        lblClass.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lblClass.setForeground(new java.awt.Color(255, 204, 0));
        lblClass.setText("Class");

        lblFaS.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        lblFaS.setForeground(new java.awt.Color(255, 204, 0));
        lblFaS.setText("Feats and Spells");

        chName.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        chName.setForeground(new java.awt.Color(255, 255, 255));
        chName.setText("Name");

        chAge.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        chAge.setForeground(new java.awt.Color(255, 255, 255));
        chAge.setText("Name");

        chRace.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        chRace.setForeground(new java.awt.Color(255, 255, 255));
        chRace.setText("Name");

        chFaS.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        chFaS.setForeground(new java.awt.Color(255, 255, 255));
        chFaS.setText("Name");

        chClass.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        chClass.setForeground(new java.awt.Color(255, 255, 255));
        chClass.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFaS)
                    .addComponent(lblClass)
                    .addComponent(lblRace)
                    .addComponent(lblAge)
                    .addComponent(lblName)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chFaS)
                            .addComponent(chClass)
                            .addComponent(chRace)
                            .addComponent(chAge)
                            .addComponent(chName))))
                .addGap(251, 251, 251))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chName)
                .addGap(13, 13, 13)
                .addComponent(lblAge)
                .addGap(4, 4, 4)
                .addComponent(chAge)
                .addGap(18, 18, 18)
                .addComponent(lblRace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chRace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClass)
                .addGap(2, 2, 2)
                .addComponent(chClass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFaS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chFaS)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    
    
    public void extract(ArrayList<String> feats){
        String word = "";
        for (String feat : feats){
            word += feat + " | ";
            
        }
        
        chFaS.setText(word);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharacterSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharacterSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chAge;
    private javax.swing.JLabel chClass;
    private javax.swing.JLabel chFaS;
    private javax.swing.JLabel chName;
    private javax.swing.JLabel chRace;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblFaS;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRace;
    // End of variables declaration                   
}
